# Configure variables for this example and build using generic makefile

APP_NAME           = ExecProcedures
APP_FORM           = ExecProceduresForm
XL                 = 0
ENGINE             = 1

include make.dotnet

