# Configure variables for this example and build using generic makefile

APP_NAME           = ExecProgram
APP_FORM           = ExecProgramForm
XL                 = 0
ENGINE             = 1

include make.dotnet

